version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "geocoder-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rr249c6daol6"
s3_prefix = "geocoder-sam"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
